### ISSUE TITLE
Not working command "movie markdown"

### ISSUE THREAD

**Issue by sakuramochi708** [ueckoken/KokenWiki#166]
For example page: https://wiki.koken.club.uec.ac.jp/%E5%86%85%E9%83%A8/%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88/%E3%81%BE%E3%81%A4%E3%82%8A/ 

I think this command "?\[hogehoge\]\(./hogehoge.mp4\)" is not working. Picture command "\!\[hoge\]\(./hoge.jpg\)" is working.

**Comment by otariidae** [comment]
`?[title](./path/to/movie.mp4)` is invalid Markdown. This is an old syntax of customized, extended, out-of-specs Markdown parser.
