### ISSUE TITLE
Fix or change token url

### ISSUE THREAD

**Issue by sakuramochi708** [ueckoken/KokenWiki#206]
招待トークンを発行したとき、wiki.kokenのURLではなく、appspot.comの方で発行される。

細かいところではありますが、よろしくお願いします。

**Comment by sakuramochi708** [comment]
（wiki.kokenのほうでトークンを発行してほしいということです）

**Comment by otariidae** [comment]
looks like it depends on domain you access.
if you access wiki.koken you will get wiki.koken invitation URL.
if you access appspot you will get appspot invitation URL.
