### ISSUE TITLE
Moving the location of a user group

### ISSUE THREAD

**Issue by sakuramochi708** [ueckoken/KokenWiki#207]
親ディレクトリの位置の下、本文記入の上の位置に「閲覧可能グループ」「編集可能グループ」の選択を持ってくる。
おそらく、運営ディレクトリのグループの付け忘れが目立つので、少しでも目立つところに持ってきた方がよいと思いました。

**Comment by Azuki-bar** [comment]
修正はこのあたりをいじれば出来ます。
https://github.com/ueckoken/KokenWiki/blob/4abede47a5a89ee0e29484fbb7f1b56b7a3425f1/app/javascript/components/MdEditor/MdEditor.tsx#L104-L147

**Comment by sakuramochi708** [comment]
（こちらは @ybasviel さんの意見ですので、質問はそちらにお願いします）
