### ISSUE TITLE
Moving the location of a user group

### ISSUE THREAD

**Issue by Azuki-bar** [ueckoken/KokenWiki#210]
relate #207 #208 

![image](https://user-images.githubusercontent.com/42642269/156937646-351a43f1-2d53-4fb8-ac3a-86d69a5b7ac9.png)

**Comment by Azuki-bar** [comment]
group selectors are not moving to the top of the editor.

**Comment by Azuki-bar** [comment]
this issue is already cleared. on #208

**Comment by otariidae** [comment]
marually edited deploy version

very frequent merges can confuse the order of deployment
