### ISSUE TITLE
KokenWikiのファイルアップロード問題

### ISSUE THREAD

**Issue by sakuramochi708** [ueckoken/KokenWiki#63]
ファイルを参照して「送信」ボタンを押してもうんともすんとも言わないですね。
送信したファイルは.pptxですが、禁止文字は含まれていないので通常ならアップロードできるのかなと思います。

おそらくクラウド移設による弊害が起きてるのかなと感じています。よろしくお願いします

**Comment by otariidae** [comment]
Turned out this was caused by uploading a large file.
Not a bug.
